# Generated by Django 5.0 on 2023-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notificacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='notificacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificacion'),
        ),
    ]
